### ISSUE TITLE
Travis job failed.

### ISSUE THREAD

**Issue by irshadpc** [cyclefortytwo/ironbelly#30]
@i1skn  Please look on this [issue](https://travis-ci.com/cyclefortytwo/ironbelly/jobs/193617477).

**Comment by irshadpc** [comment]
@i1skn any comment on these issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by i1skn** [comment]
@irshadpc tests in travis ci are still failing, need to be fixed.

**Comment by irshadpc** [comment]
@i1skn my concern was why this issue didn't go away. I was inspecting the latest build from Travis and I found out build process was canceled. @i1skn  any specific reason to do the above this I mentioned.

**Comment by i1skn** [comment]
@irshadpc the issue did go away, but was reintroduced in the latest commit (some problem with npm dependency). The build was canceled, because when I tag a commit - travis would initiate two builds: one for the master branch and one for the tag. So I’m cancelling one of them usually. Probably, I can configure to only run it on either of them - need to check. Regarding the issue - feel free to help to fix it!

**Comment by irshadpc** [comment]
@i1skn let me check and update here.

**Comment by irshadpc** [comment]
https://github.com/cyclefortytwo/ironbelly/pull/39

**Comment by irshadpc** [comment]
https://github.com/cyclefortytwo/ironbelly/pull/39
